version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    command: sh -c "\
      until nc -z db 5432; do echo 'Waiting for db...'; sleep 1; done && \
      python manage.py migrate --noinput && \
      python manage.py collectstatic --noinput && \
      gunicorn --bind 0.0.0.0:8000 app.wsgi:application"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  web-dev:
    build: .
    restart: always
    command: sh -c "\
      until nc -z db 5432; do echo 'Waiting for db...'; sleep 1; done && \
      python manage.py migrate --noinput && \
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  staticfiles:
  media:
