name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit checks
        run: make pre-commit

      - name: Run tests with coverage
        env:
          SECRET_KEY: "dummy-key-for-ci"
          SQL_DATABASE: "dummy_db"
          SQL_USER: "dummy_user"
          SQL_PASSWORD: "dummy_password"
          SQL_HOST: "dummy_host"
          SQL_PORT: "1234"
          MERCHANT_WHATSAPP_NUMBER: "5511999999999"
          EXTERNAL_API_BASE_URL: "https://api.exemplo.com"
        run: make test-coverage
