# Generated by Django 5.2.1 on 2025-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Se este produto deve ser exibido para clientes sem login', verbose_name='Visível publicamente?'),
        ),
    ]
